package com.fittrack.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * Represents a registered user in the FitTrack system.
 * Maps to the 'users' database table.
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /**
     * Unique identifier auto-generated by the database identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User's full display name.
     */
    @Column(nullable = false)
    private String name;

    /**
     * User's unique email address, used as login username.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * BCrypt hashed password string.
     */
    @Column(nullable = false)
    private String password;
}
